### ISSUE TITLE
does freeCAD has a design reference that can be used to improve the UI. I am personally interested 

### ISSUE THREAD

**Issue by theabhayprajapati** [FreeCAD/FreeCAD-Homepage#104]
I am interested in improving the UI for the homepage, any design reference.

**Comment by yorikvanhavre** [comment]
Working on the UI is always welcome! However, there are no real "guidelines" or references, other than what you can see there, on both the website and the application. Go ahead and propose something! However, UI matters are always sensible and usuallyecreate a lot of heated debate. so to avoid a lot of frustration on your part, I would advice to go slowly, by small increments, and discuss and show your ideas on the [forum](https://forum.freecad.org) before implementing something

**Comment by theabhayprajapati** [comment]
Thanks @yorikvanhavre is soo start improving the UI as I find.

**Comment by chennes** [comment]
There is a Style page in the Developer's Handbook: https://freecad.github.io/DevelopersHandbook/stylebook/

Please help us improve both it and the UI!
