### ISSUE TITLE
discord link is broken

### ISSUE THREAD

**Issue by theabhayprajapati** [FreeCAD/FreeCAD-Homepage#105]
the current discord link is broken [current Link](https://discord.com/invite/NpMefpXWFT)

what may be the error?
Most probably the link has expired.

**Comment by theabhayprajapati** [comment]
step to reproduce :
https://www.freecadweb.org/ -> **community**  on header section -> discord

**Comment by yorikvanhavre** [comment]
I don't know much about discord... What should be the correct link?

**Comment by theabhayprajapati** [comment]
Hi, @yorikvanhavre just set the expiration setting to NEVER and everything will work fine.

 It can be done in 10 seconds by following these steps 🔽
[discord-expire-never](https://www.youtube.com/watch?v=5GyfB05RSPQ) 
simple 10 secs video.

**Comment by donovaly** [comment]
@yorikvanhavre , I assume you must now update the webpage according to the merged PR, right?

**Comment by yorikvanhavre** [comment]
Done!
