### ISSUE TITLE
missing option in git clone command on wikipage for libredwg

### ISSUE THREAD

**Issue by maser111** [FreeCAD/FreeCAD-Homepage#109]
In the wiki page [https://wiki.freecadweb.org/FreeCAD_and_DWG_Import#Installation_Linux.2FUnix_systems](https://wiki.freecadweb.org/FreeCAD_and_DWG_Import#Installation_Linux.2FUnix_systems) the command for `git clone` is missing for the `--recurse-submodules` option.

**Comment by luzpaz** [comment]
@maser111 so it should be `git clone --recurse-submodules https://git.savannah.gnu.org/git/libredwg.git` is what you're indicating ?

Note: not the place for this. better to post to the forum next time, but nm. thank you for the feedback

**Comment by luzpaz** [comment]
I've updated the wiki page. Thanks!
