### ISSUE TITLE
Documentation-dropdown is cut off on mobile phones

### ISSUE THREAD

**Issue by Glitchy-Tozier** [FreeCAD/FreeCAD-Homepage#116]
See screenshots.
This behaviour happens in all browsers (FF, FF Klar, Brave, DuckDuckGo) I tested on my Samsung Galaxy S9. I was even able to reproduce in on PC by making the window narrow enough to left-align the `Documentation`-dropdown-button.

![brave](https://user-images.githubusercontent.com/59611881/200192458-716b41a7-7da1-4516-9c5f-660c2d12c861.jpeg)
![ddg](https://user-images.githubusercontent.com/59611881/200192461-17da91bc-bbfc-4175-b8ce-b77a45e24b2c.jpeg)
![ff](https://user-images.githubusercontent.com/59611881/200192463-112ab24b-2d5e-4784-a21f-4d1548aa6566.jpeg)

**Comment by luzpaz** [comment]
Anyone interested in tackling this ?

**Comment by sliptonic** [comment]
Is this not the same as https://github.com/FreeCAD/FreeCAD-Homepage/pull/115
I merged yesterday but not sure if Yorik has updated the site yet.

**Comment by Glitchy-Tozier** [comment]
> Is this not the same as https://github.com/FreeCAD/FreeCAD-Homepage/pull/115
> I merged yesterday but not sure if Yorik has updated the site yet.

I guess you're right, it was already reported. Seems like I overloojed that duplicate: https://github.com/FreeCAD/FreeCAD-Homepage/issues/72#issuecomment-1262626203

Closing this issue!
