### ISSUE TITLE
FreeCAD Board Administrator link is broken

### ISSUE THREAD

**Issue by fester225** [FreeCAD/FreeCAD-Homepage#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
If you continue to have problems please contact the Board Administrator.
```

### Subproject(s) affected?

None

### Problem description

Clicking on the Board Administrator link leads to: You cannot send another email at this time. Please try again later.

How many days do I need to wait before the link will start to work?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
@fester225 what is your username on the forums? I will look to see if there is a problem with the group settings.

**Comment by fester225** [comment]
fester225

**Comment by chennes** [comment]
There is no user at the forums with that username -- can you double-check?
https://forum.freecadweb.org/memberlist.php?mode=searchuser&username=fester225

**Comment by fester225** [comment]
On the one hand, the username is incorrect. On the other it is already in use. How can it be both incorrect and in use?

￼


￼

**Comment by chennes** [comment]
So that we don't expose any private contact information here on GitHub, it's probably best to resolve what I presume is a login issue via another channel. Can you please contact me at chennes@freecad.org and we can try to get your account situated?
