### ISSUE TITLE
[Change] Error 404 page

### ISSUE THREAD

**Issue by AdarshRawat1** [FreeCAD/FreeCAD-Homepage#121]
Incorporating a 404 error page featuring the FreeCAD logo, a clear option to return to the home page, and a footer displaying contact details can enhance user experience and simplify navigation on the website. 
 
 Current 404 error page -
 
![image](https://user-images.githubusercontent.com/100958893/226090298-901959e7-e6ed-4f30-8d64-af42c0b3c198.png)
 

I would like to revamp the error 404 page of the website.

**Comment by yorikvanhavre** [comment]
That's a good idea!
I would make it as much as possible look like the FreeCAD homepage, for ex. using the same header and footer includes

**Comment by AdarshRawat1** [comment]
Actually, I was planning to make a PR .
I was waiting for a approval, allow me handle this feature change.

**Comment by luzpaz** [comment]
@AdarshRawat1 any progress ?

**Comment by AdarshRawat1** [comment]
@luzpaz I'll make a PR soon

**Comment by AdarshRawat1** [comment]
@luzpaz @yorikvanhavre  Which of the following SVGs should I use.
![image](https://user-images.githubusercontent.com/100958893/227759198-c4f83329-0451-4f44-8528-c584d2b7209b.png)

And maybe we can also combine it with a maintenance SVG- 
![image](https://user-images.githubusercontent.com/100958893/227759085-7bee33fd-5c2e-4c19-95c8-10286ea90a1f.png)

**Comment by AdarshRawat1** [comment]
@yorikvanhavre @luzpaz 
kindly suggest necessary changes.

**Comment by yorikvanhavre** [comment]
As a general rule it's always better to use a graphic you made yourself. In an open-source project, we have to take great care that everything you do is properly licensed with an open license.
I would use something that suggests an error, like number 2
