### ISSUE TITLE
Broken download link for macOS Intel version 0.21.0

### ISSUE THREAD

**Issue by tripplilley** [FreeCAD/FreeCAD-Homepage#131]
The link to the DMG for version 0.21.0 for Intel macOS is broken. Depending on your perspective, this is either because the link lacks an extra dash (`-`) before `-mac`, or the release asset in the FreeCAD/FreeCAD repository has an extra dash in that same place.

It looks like this is because earlier versions had an extra field in the release name to describe the installer variant (`-conda`), but when they removed it, they forgot to strip the separator.

As a practical matter, because the Homebrew formula scrapes the downloads page, this also breaks the Homebrew installer.

**Comment by chennes** [comment]
Oops, missed that in the last upload. I will correct it now, thanks for the catch.

**Comment by chennes** [comment]
Can you please re-test and ensure it's working now?

**Comment by tripplilley** [comment]
Looks good, thanks!
