### ISSUE TITLE
Documentation for web devs interested working on FreeCAD webpage

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-Homepage#135]
_Originally posted by @marcuspollio in https://github.com/FreeCAD/FreeCAD-Homepage/issues/134#issuecomment-1738336010_

As I struggled a bit to find a way to open the php file locally, here is a small hint for anyone looking to open a website folder (FreeCAD Homepage for example) on his web browser without using Apache, XAMPP or others :

1) download the repository (< > Code green button on Github) and unzip
2) make sure php is installed (for me on GNU/Linux, I had to install "php8.1-cli" as of September 2023)
3) go to my local copy of the website folder ("FreeCAD-Homepage-master" in this case)
4) open the terminal at working-directory location and paste `php -S 127.0.0.1:8000`
5) as there is an "index.php" file in the FreeCAD case, opening a new tab in your web browser with `localhost:8000/` displays the web page correctly. If you want to reach a particular file, use `localhost:8000/MyFile.php`

Hope it helps other folks... And sorry for the off-topic XD

**Comment by chennes** [comment]
Let's get it into the Handbook someplace.

**Comment by AdarshRawat1** [comment]
How about Adding screenshots for easier understanding.

**Comment by marcuspollio** [comment]
Hi !

Please find below an update with some screenshots for this:

1. Fork the original repository to your personal GitHub account:

![01](https://github.com/FreeCAD/FreeCAD-Homepage/assets/131592747/4fcd63c9-f9c0-46d7-afbf-b9134303b298)


1a. If you don't have an account or prefer to inspect and modify files locally without relying on GitHub's features, download the compressed folder :

![02](https://github.com/FreeCAD/FreeCAD-Homepage/assets/131592747/d09c306a-7dcf-41b5-b6f3-c90629edd5ea)


2. From GitHub Desktop app, clone the fork you just created (skip this step if you downloaded the zip in step 1a) :

![03](https://github.com/FreeCAD/FreeCAD-Homepage/assets/131592747/c2c8bbec-8492-4a7d-af08-95d5fba88b0a)


3. Make sure php is installed (for me on GNU/Linux, I had to install "php8.1-cli" as of September 2023)

4. Go to your local cloned copy of the repository, in the folder you specified previously ("FreeCAD-Homepage" in this case), and open the terminal at working-directory location :

![05](https://github.com/FreeCAD/FreeCAD-Homepage/assets/131592747/e7b49f59-79c0-41ba-90bc-e57cdddd0965)


5. Paste `php -S 127.0.0.1:8000`

![06](https://github.com/FreeCAD/FreeCAD-Homepage/assets/131592747/28b2ea67-f36d-4960-8fcc-3205187df2ca)


6. As there is an "index.php" file in the FreeCAD case, open a new tab in your web browser with `localhost:8000` to display the web page correctly. If you want to reach a particular file, use `localhost:8000/MyFile.php`

![07](https://github.com/FreeCAD/FreeCAD-Homepage/assets/131592747/4d973c79-f5b6-4ad2-a26f-94cb9f47ad73)

Note that the translated pages do not work.

**Comment by chennes** [comment]
Go for it!

**Comment by marcuspollio** [comment]
Hi @luzpaz !
Could you please close this issue now ?
I added the Fix # thingy in my PR above but it looks like this does not work across different repos... sorry =D
Thanks !
