### ISSUE TITLE
other flag.jpg -> 403 Forbidden

### ISSUE THREAD

**Issue by benny-de** [FreeCAD/FreeCAD-Homepage#143]
Hello FreeCAD Team,

when you switch the language via the flag graphic top right of the site, on the localized pages the flag graphic will not be shown.

The default, flag of Great Britain, works: https://www.freecad.org/lang//flag.jpg
but for example:
img src="lang/?lang=de/flag.jpg" --> https://www.freecad.org/lang/?lang=de/flag.jpg  => 403 Forbidden
https://www.freecad.org/lang/de/flag.jpg works

img src="lang/?lang=af/flag.jpg" --> https://www.freecad.org/lang/?lang=af/flag.jpg => 403 Forbidden
https://www.freecad.org/lang/af/flag.jpg works
...

Either the HTML img src link is wrong (lang/?lang=af/flag.jpg => lang/af/flag.jpg) or you have to check the file permissions on the webserver.

Thank you very much.

Regards, Benny

**Comment by chennes** [comment]
@yorikvanhavre do you know what's going on here? I haven't looked at how those flags are displayed.

**Comment by yorikvanhavre** [comment]
Fixed!
