### ISSUE TITLE
Forum search seems to be broken

### ISSUE THREAD

**Issue by arkadesOrg** [FreeCAD/FreeCAD-Homepage#150]
![broken_search](https://github.com/FreeCAD/FreeCAD-Homepage/assets/6597386/4ca1ebbd-4f73-4fde-9844-fc3308231e19)

**Comment by yorikvanhavre** [comment]
That's unfortunately a problem with the forum software we use, phpBB. There is no way for us to change this. We always suggest using google or any other search engine with `site:forum.freecad.org` or in duckduckgo, `!fc`
