### ISSUE TITLE
Remove space character please

### ISSUE THREAD

**Issue by fastGEAR** [FreeCAD/FreeCAD-Homepage#154]
https://github.com/FreeCAD/FreeCAD-Homepage/blob/ff4113aacb1a7c39b081d0652fd5a7627238c5fd/lang/ru/LC_MESSAGES/homepage.po#L443C1-L444C1

**Comment by yorikvanhavre** [comment]
Translations are handled on https://crowdin.com/project/freecad - You can even fix the translation yourself at https://crowdin.com/translate/freecad/27908/en-ru?filter=basic&value=0 ;)

I'll close this issue as it does not require action here.
