### ISSUE TITLE
Flag

### ISSUE THREAD

**Issue by Cdccic** [FreeCAD/FreeCAD-Homepage#172]
When we open the main page od FreeCad from the browser, the flag of the language is not dispalyed.

![sreenshot](https://github.com/FreeCAD/FreeCAD-Homepage/assets/168284022/c04add48-791e-48c7-ba75-1be0bd09a111)

But when we change the language, the flag is now displayed.

The first time the url is https://www.freecad.org/?lang=fr_FR and the second time is https://www.freecad.org/index.php?lang=fr.
My browser is Google Chrome 126.0.6478.62 and I live in France.

**Comment by yorikvanhavre** [comment]
The problem here is https://www.freecad.org/?lang=fr_FR ... Where does that URL come from?

We could add a system so if no fr_FR flag is found, then fr is used automatically, though. I'll have a look if that's easy or not
