### ISSUE TITLE
current download link is dead

### ISSUE THREAD

**Issue by 1tylermitchell** [FreeCAD/FreeCAD-Homepage#174]
Freecad.org - Download button links to a location that has a typo in it:
https://www.freecad.org/downloads.phpen

https://www.freecad.org/downloads.php - this works, so looks like a language tags is getting added by mistake or is not being processed correctly.

**Comment by 1tylermitchell** [comment]
Umm, looks like other links on the site have the same problem too!

**Comment by chennes** [comment]
@kkremitzki orr @yorikvanhavre any idea why this is happening?

**Comment by deltafactory** [comment]
@chennes It's related to the locale code moved to translation.php. Specifically, `$lang = 'en';` which is appended to the URLs in header.php.

Prior to the latest commit, I believe $lang would either be blank or set to a querystring parameter based on the language specified in `$_GET['lang']` (i.e. ?lang=en).

**Comment by deltafactory** [comment]
PR #175 looks like it should fix this with minimal changes.

**Comment by kkremitzki** [comment]
Broadly speaking, we have a variable type overload--`$lang` is being used to store an ISO 639 language code like `"en"`, but also a URL query string like `"?lang=en"`.

**Comment by kkremitzki** [comment]
Temporary workaround to this pushed via https://github.com/FreeCAD/FreeCAD-Homepage/commit/4e90896b61e7355f1f4088b598fd7bfb41ff057c but leaving this open for discussion on the underlying issue I mentioned in the previous comment
