### ISSUE TITLE
Wrong fillet and chamfer edges selected by FreeCAD RC1/v1.0 when opening older FreeCAD files.

### ISSUE THREAD

**Issue by TadPath** [FreeCAD/FreeCAD-Homepage#219]
The problem is that some models in FreeCAD files made with pre-RC1 FreeCAD, when opened with the latest RC1/v1.0 version show errors in some fillets and chamfers. When looking into those errors it is that RC1/v1.0 assigns (shows as selected) the wrong edges for the applied chamfers and fillets ('wrong' as in not the edges originally selected in the file as when it was created in pre-RC1/v1.0 FreeCAD).
In other words RC1/v1.0 FreeCAD wrongly assigns edges for chamfers and fillets for models created in older FreeCAD versions.
![Pre_RC1_ChamferProblem](https://github.com/user-attachments/assets/900b0373-9f0e-4a0c-9421-ccb8f997f7a1)
![RC1_NoChamfers](https://github.com/user-attachments/assets/7b0e35dc-ad7d-46fe-b990-2c1839b92a6e)
![Fixed_manually_RC1](https://github.com/user-attachments/assets/6859ae77-4a33-40e1-9e90-a94a26f85571)
![Pre_RC1b_FilletProblem](https://github.com/user-attachments/assets/2a6c974b-dd92-4354-b6e7-fe27ec3e23c3)
![PreRC1b_WrongEdges](https://github.com/user-attachments/assets/54339b39-8d07-4999-aad6-0b54ed857a03)
![PreRC1b_WrongEdges2](https://github.com/user-attachments/assets/6b105e5f-5a70-481a-bc7e-271d620250b1)
![PreRC1b_Manual_correction1](https://github.com/user-attachments/assets/1541d6c8-5235-4ddb-b98c-bb13ece01f51)
I attach some screenshots to explain. Also you may download the FreeCAD files used for this from my Google Drive with [this link](https://drive.google.com/drive/folders/15nRBnC0SqlMsNcmElwT500wWt-M28eap?usp=sharing)

The pictures from top to bottom show:
1. What the problem looks like in RC1/v1.0 before fixing for fillets - the correct shapes are shown in the render but the model tree shows error
2. When opening the erroneous chamfer in RC1/v1.0 it shows not edges selected at all
3. Manually fixed by re-adding the edges
4. What the fillet problem looks like when opening in RC1/v1.0 - note the correct filleted shape is shown in the render but the model tree shows error on the fillet
5. The view when opening the erroneous fillet in RC1/v1.0 shows that edges are selected but these do not correspond to those edges shown filleted in the previous picture
6. Another view of the opened erroneous fillet
7. The view after deleted all selected edges and re-assigned them manually. The result is good (the render is as was shown in picture 4 and the error in the model tree gone after this - picture not shown).

The files in the Google drive folder are:
Pre_RC1.FCStd - the chamfer problem file before being fixed
Manually_fixed_RC1.FCStd - the chamfer problem file after manual fixing in RC1/v1.0
Pre_RC1b.FCStd - the fillet problem file before being fixed
Manually_fixed_RC1b.FCStd - the fillet problem file after manual fixing in RC1/v1.0

Note 1: ALL these files were saved with RC1 (I had to extract the models from very large files and save them in separate files for the purpose of making this issue).

Note 2: I cannot 'downgrade' back to pre RC1 to tell you exactly what version of FreeCAD they were made in but is was probably an 0.21 version).

Note 3: The specific version of FreeCAD this issue pertains to (what I call RC1/v1.0 in the above) is:

 OS: Arch Linux (LXDE/LXDE/xcb)
Architecture: x86_64
Version: 1.0.0.39109 (Git)
Build type: Release
Branch: makepkg
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.12.7, Qt 6.8.0, Coin 4.0.3, Vtk 9.3.1, OCC 7.8.1
Locale: English/United Kingdom (en_GB)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/fusion
Installed mods: 
  * fasteners 0.5.29
  * OpticsWorkbench 1.0.24

Thanks.

**Comment by Reqrefusion** [comment]
@TadPath I think there was confusion, this is the repo of the site, the correct repo is https://github.com/FreeCAD/FreeCAD. I think @chennes or @maxwxyz can carry it.

**Comment by TadPath** [comment]
Sorry. My mistake. I will open the issue on the correct site.
Thanks for pointing it out.
