### ISSUE TITLE
letsencrypt isn't automated / automation is broken

### ISSUE THREAD

**Issue by ThisGuyCodes** [FreeCAD/FreeCAD-Homepage#28]
cert expired

![image](https://user-images.githubusercontent.com/450860/44013654-d03fca30-9e94-11e8-93a0-e38660be95a3.png)

**Comment by luzpaz** [comment]
Yeah, this is an issue. I can't connect via mobile

**Comment by Nemesis81** [comment]
Can't connect with anything

**Comment by luzpaz** [comment]
@kkremitzki urgent

**Comment by chennes** [comment]
Fixed (many moons ago :) ).
