### ISSUE TITLE
Add links to this github repo from the website (so users can improve)

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-Homepage#34]
Have a link at the bottom of each webpage linking to their corresponding source file in https://github.com/FreeCAD/FreeCAD-Homepage
That way users can quickly fork and add content

**Comment by luzpaz** [comment]
@theabhayprajapati what does it entail?  
@yorikvanhavre shall we do this?

**Comment by AdarshRawat1** [comment]
@luzpaz @theabhayprajapati @yorikvanhavre 
Do you plan on adding this feature?
If yes, then I can tackle this issue.

**Comment by theabhayprajapati** [comment]
> @luzpaz @theabhayprajapati @yorikvanhavre 
> Do you plan on adding this feature?
> If yes, then I can tackle this issue. 

always go ahead no need of permissions

**Comment by AdarshRawat1** [comment]
@yorikvanhavre @luzpaz @theabhayprajapati What are your suggestions for the placement of the edit code Link?
I have listed some, please provide your feedback. (Currently I have used `footer.php` for placement of edit links, to avoid editing each file individually)
 
1. - ![image](https://github.com/FreeCAD/FreeCAD-Homepage/assets/100958893/0c4828d6-8049-4678-aa09-3d71e7a57eb6)
2. - ![image](https://github.com/FreeCAD/FreeCAD-Homepage/assets/100958893/1b8cfc08-82b4-4807-a902-9da1f94b669f)
3. - ![image](https://github.com/FreeCAD/FreeCAD-Homepage/assets/100958893/d4b9d70b-b40b-49cf-88e8-3737a19dc795)
4. - ![image](https://github.com/FreeCAD/FreeCAD-Homepage/assets/100958893/4f78a311-07f2-4717-b2e8-97f2851f60b2)

**Comment by theabhayprajapati** [comment]
4th one from my side, 

easy to know what to do without reading.
