### ISSUE TITLE
Add social media icons to the navbar

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-Homepage#35]
- [ ] Twitter #24  
- [ ] Mastodon
- [ ] Reddit
- [ ] IRC || Gitter.im || Riot/Matrix 
- [ ] Github stars
- [ ] Github repo

**Comment by sariug** [comment]
![image](https://user-images.githubusercontent.com/14132181/69384847-c0ba2b80-0cbd-11ea-9de0-f6010d5dbd08.png)

All seem to be here. Lets close it ?

**Comment by luzpaz** [comment]
It's in the footer but that's fine
