### ISSUE TITLE
Add new sha256 hashes to downloads.php

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-Homepage#39]
![image](https://user-images.githubusercontent.com/4140247/58639006-1213d000-82c4-11e9-9d51-d229e0f99080.png)

![image](https://user-images.githubusercontent.com/4140247/58639161-6a4ad200-82c4-11e9-85c5-ba245807ce49.png)

**Comment by chennes** [comment]
Obsolete.
