### ISSUE TITLE
Have a widget that shows latest FreeCAD dev blog posts on the website

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-Homepage#42]
Lets have a place on the website that lists the latest development blog posts from https://freecad.github.io

FreeCAD Development Blog:  https://freecad.github.io
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=10&t=36907

**Comment by yorikvanhavre** [comment]
Yes, for me this is done already, we have a well-placed link to the blog, where people would expect to find it... Having a kind of widget would complexify things with little benefit IMHO.

What I would like is to have the blog better shown on the FreeCAD start page. But that's for another issue.. :)

I let you guys decide, but for me we can close this as done...

**Comment by luzpaz** [comment]
Fair. Closing.
