### ISSUE TITLE
Reason to migrate FC to a different host 

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-Homepage#50]
commit 3364907 hasn't permeated to the [webpage](https://freecadweb.org/downloads.php)
CC @sgrogan @kkremitzki 
Note: Links are not up to date either.
![image](https://user-images.githubusercontent.com/4140247/68992658-406a7500-083c-11ea-9967-05c36b57bb18.png)

**Comment by sgrogan** [comment]
I think @kkremitzki or @yorikvanhavre needs to do this.

**Comment by luzpaz** [comment]
@yorikvanhavre may I have permission to help expedite these type of issues?

**Comment by kkremitzki** [comment]
I am adding some CI so this gets done automatically.

**Comment by kkremitzki** [comment]
It doesn't look like FTP pushing out of Travis is going to work for our current hosting provider; we are using FTP with SSL and not SFTP, which requires SSH. See https://blog.travis-ci.com/2018-07-23-the-tale-of-ftp-at-travis-ci

**Comment by luzpaz** [comment]
it's amazing we've been able to swing things via FTP this long. I guess it's time to move... ?

**Comment by kkremitzki** [comment]
I would love to. It's just a big, multi-stage process.

**Comment by luzpaz** [comment]
time to draw up a proposed timeline and see who can volunteer to help with each phase

**Comment by luzpaz** [comment]
> I am adding some CI so this gets done automatically.
> 
> It doesn't look like FTP pushing out of Travis is going to work for our current hosting provider; we are using FTP with SSL and not SFTP, which requires SSH. See blog.travis-ci.com/2018-07-23-the-tale-of-ftp-at-travis-ci

@kkremitzki thanks for the attempt 
![image](https://user-images.githubusercontent.com/4140247/70302726-c3437780-17cb-11ea-80e0-6d3c6e35ee7a.png)


@yorikvanhavre :point_up_2: another reason to consider migrating to a different server

**Comment by kkremitzki** [comment]
Stage 1: Migrate the bug tracker. Add a redirect for freecadweb.org/tracker/... URLS to point at the equivalent resource at tracker.freecadweb.org which will be on a VPS. I've tested all the pieces for this and am ready, just need to point tracker.freecadweb.org at the same IP as fra1.freecad.io and I can deploy everything else.

**Comment by luzpaz** [comment]
@kkremitzki great!

> (I don't have DNS access for freecadweb.org)

Who does have access ?

**Comment by kkremitzki** [comment]
If not Yorik then surely @wwmayer

**Comment by yorikvanhavre** [comment]
sorry guys, missed this one...
I can't change DNS records, but I sent you the host email in PM.
where exactly do you want to host the tracker @kkremitzki ? Is it really a good idea to host it where only you will manage it? Not because I don't trust you of course, but because of the burden on your shoulders only if anything goes wrong... Just thinking aloud here...

**Comment by kkremitzki** [comment]
The plan is to host at [Digital Ocean's Frankfurt datacenter](https://blog.digitalocean.com/introducing-our-new-european-region-frankfurt/) on a machine I'm currently paying for myself, `fra1.freecad.io`. However Digital Ocean has good teams support and [a track record of open source project sponsorship](https://www.digitalocean.com/open-source/) so I created a FreeCAD team and contacted them to see if we could get something for free or cheap.

I also have an [rsync.net](https://www.rsync.net/) backup account for myself in their Switzerland datacenter, and that has a recent backup of our web services. For that, appropriately limited access for e.g. you and Werner is just a matter of giving me an SSH public key, and once we move from shared hosting, automated backups with 99.9999% resiliency will become a breeze.

The services themselves will be done infrastructure-as-code style, which I've started at [FreeCAD/FreeCAD-WebServices](https://github.com/FreeCAD/FreeCAD-WebServices/). This means we can start doing things like automated deploy on pull request merge, and have manual management & local development be a matter of `git pull`, `ssh`, and `vagrant` commands. With everything documented and access appropriately shared, we should be OK.

It's a big change, but I think things could be so much better than they are now that it's worth trying.

**Comment by luzpaz** [comment]
Full speed ahead!

**Comment by yorikvanhavre** [comment]
ok I'm convinced :)
I can ask them to redirect. I also think we should pay for that hosting with freecad money.
What's the IP to redirect? fra1.freecad.io doesn't seem to work, nor freecad.io ...

**Comment by kkremitzki** [comment]
It's `104.248.47.186`.

**Comment by kkremitzki** [comment]
We may want to do this for the wiki first instead: https://forum.freecadweb.org/viewtopic.php?f=8&p=354908#p354908

**Comment by chennes** [comment]
Is there anything remaining on this ticket? I know we don't have auto-push set up, but I think everyone who can merge PRs here can also `git pull` on the server, so it's not too onerous to have that extra step.

**Comment by luzpaz** [comment]
Not sure what the status of this is.

**Comment by yorikvanhavre** [comment]
I think we can consider it done. Indeed I also wouldn't auto-push for now... I guess it wouldn't be too had to achieve when we get bored to do it manually.
