### ISSUE TITLE
All the homepage translations are broken.

### ISSUE THREAD

**Issue by Ferenc-** [FreeCAD/FreeCAD-Homepage#51]
It feels a bit surreal to report this, but if I go to https://www.freecadweb.org/,
and I select any language other than English, then basically what happens, is that with the exception of the headlines pretty much everything remains in English. 
If I go to https://crowdin.com/project/freecad and download the homepage.po, then it seems that all those homepage.po files are outdated, and they don't even contain the English text which is currently on the English homepage and is supposed to be translated. And yet the crowdin site proudly reports that the homepage.po is 100% translated into a bunch of languages.
I am guessing somebody should upload the correct homepage.po or something.

**Comment by yorikvanhavre** [comment]
on it!!

**Comment by yorikvanhavre** [comment]
ok latest strings are in! And I also updated the strings on crowdin.

**Comment by Ferenc-** [comment]
Hi @yorikvanhavre and @luzpaz 
Is it possible that essential the same problem keeps happening?
I went to crowdin again downloaded the homepage.po in a couple of different languages and again, lots of the texts are missing from that file, which appear in English on the homepage, regardless of what language you select.
