### ISSUE TITLE
Wrong href: https://www.freecadweb.org/api/http//www.freecadweb.org/wiki

### ISSUE THREAD

**Issue by MartinMajewski** [FreeCAD/FreeCAD-Homepage#55]
I found a faulty hyperlink at [https://www.freecadweb.org/api/](https://www.freecadweb.org/api/) which should direct to the Wiki-page.

It states: `https://www.freecadweb.org/api/http//www.freecadweb.org/wiki`

![Screenshot 2020-10-03 at 12 57 59](https://user-images.githubusercontent.com/2221289/94989888-2c288700-0578-11eb-91a9-585dcc9b0182.png)

**Comment by luzpaz** [comment]
@kkremitzki this looks like it's fixed in the source: https://github.com/FreeCAD/FreeCAD/blob/master/src/Doc/mainpage.dox.in#L33-L34  
Can we push the API docs again ?

**Comment by luzpaz** [comment]
CC @sgrogan

**Comment by luzpaz** [comment]
Fixed
