### ISSUE TITLE
AppImage and macOS URLs changed

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-Homepage#57]
Looks like @looooo made some changes to the AppImage and it broke some stuff. 
TODO  
- [ ] Need to change the AppImage and OSX links on the downloads.php page
- [ ] Need to update the AppImage wiki page 
- [ ] Need to update the AppImage wiki script

**Comment by looooo** [comment]
Sorry I was not aware oft this. Something to remeber for newer releases.
