### ISSUE TITLE
Add a ribbon to download.php page above the fold recommending d/ling v0.19

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-Homepage#59]
We've gotten to a point where we are asking users to install and use v0.19 on the forum. Might as well just do it at the source, the download page.

**Comment by luzpaz** [comment]
The idea is a non-invasive ribbon that orients users to use v0.19 and show it in a visible location. It would especially orient Path and FEM users since v0.19 is recommended for those workbenches. Thoughts?

CC @yorikvanhavre @wmayer

**Comment by chennes** [comment]
I'm going to close this as obsolete (though I guess the same thing could be said for 0.21...)
