### ISSUE TITLE
homepage: convert kiwichat logo in to an icon that fits the footer social links?

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-Homepage#69]
kiwichat logo: https://kiwiirc.com/img/logo.png

![image](https://user-images.githubusercontent.com/4140247/113578042-34798180-95f0-11eb-959a-aa426fd8d6f3.png)  
Adding icon that allows connecting to IRC via Kiwichat freenode webchat

**Comment by luzpaz** [comment]
maybe this approach doesn't make sense. What about just changing the irc link from irc:// to the kiwichat link. Then folks who are used to IRC will just fire up their own clients manually.

**Comment by chennes** [comment]
Is this still relevant? I don't know anything about kiwichat, but the link on the page is still irc://irc.libera.chat/freecad

**Comment by luzpaz** [comment]
*shrug*  
I guess
