### ISSUE TITLE
Non uniform horizontal offsets

### ISSUE THREAD

**Issue by ElectricCookie** [FreeCAD/FreeCAD-Homepage#72]
Hey guys 👋🏻,

just a very minor design thing I noticed: The content on the page is not uniformly spaced from the page  sides.  

Specifically the horizontal space in Navbar, Footer, Headers and Featurette do not match. 

I know this is very minor, but it throws off the layout IMO 😉

**Comment by yorikvanhavre** [comment]
I can't see the problem you report... Mind to show on a screenshot?

**Comment by theabhayprajapati** [comment]
![Screenshot_20220929-232853_Chrome](https://user-images.githubusercontent.com/88815641/193107315-3f995ec3-d992-4083-a291-ec41096b64ee.jpg)



I guess he means this that the dropdown is overflowing the screen horizontally.

**Comment by luzpaz** [comment]
@ElectricCookie want to submit a PR ?

**Comment by theabhayprajapati** [comment]
can I send a **PR** I have tried to solve it?
<img width="216" alt="image" src="https://user-images.githubusercontent.com/88815641/194751663-43de9f5c-3447-4ece-b133-a071726c4a25.png">
<img width="180" alt="image" src="https://user-images.githubusercontent.com/88815641/194751777-e984bc84-0cfa-4dea-adf4-61dbee8826c0.png">
