### ISSUE TITLE
Navigation item spacing

### ISSUE THREAD

**Issue by ElectricCookie** [FreeCAD/FreeCAD-Homepage#73]
Hey guys 👋🏻,

<img width="317" alt="image" src="https://user-images.githubusercontent.com/18628516/117217246-5b9abd00-ae01-11eb-951d-dcd39b18cb24.png">

Another small design "issue" (this might be subjective) I found the that there's no spacing between the navigation items in the Navbar (only visible when hovering over several nav in quick succession).

**Comment by luzpaz** [comment]
Feel free to send a PR

**Comment by theabhayprajapati** [comment]
I can solve it.

**Comment by luzpaz** [comment]
> Feel free to send a PR

**Comment by chennes** [comment]
This never got submitted as a PR -- @theabhayprajapati do you plan on doing so, or should I close this issue?

**Comment by AdarshRawat1** [comment]
@chennes do you think this is worth fixing? If yes, then I can send a PR.

**Comment by chennes** [comment]
@AdarshRawat1 If you want to do it, go for it 🙂
