### ISSUE TITLE
 Named constraints are only displayed in other sketches if they are written out in full 0.19.1

### ISSUE THREAD

**Issue by SeibeGitHub** [FreeCAD/FreeCAD-Homepage#75]
excample if i name a constraint in sketch0 like "width" and i like to call this in sketch1 i have to wrtite
sketch0.constraint.width completly, in Version 18 it was shown if i write sketch0.constraint.w after this i get a list where i can chose "width".

**Comment by luzpaz** [comment]
Wrong place. Post to the forum.freecadweb.org

**Comment by SeibeGitHub** [comment]
thanks
