### ISSUE TITLE
Migrate wiki and forum to `freecad.org`

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-Homepage#94]
> This is not a nginx issue but a software issue. Most software like mediawiki or phpbb allow for only one "built-in" domain and won't work well with others. So far these two apps still have freecadwb.org as their default. So usually logins and other session-aware functionality won't work that well on freecad.org. It's actually time to switch I think...

_Originally posted by @yorikvanhavre in https://github.com/MariwanJ/Design456/issues/78#issuecomment-1173798969_

**Comment by yorikvanhavre** [comment]
Note to self:
* For mediawiki: change $wgServer in LocalSettings.php
* For phpBB: ACP -> Server settings -> Domain name

**Comment by luzpaz** [comment]
Will this render the search engine links broken ? Or will they redirect?

**Comment by yorikvanhavre** [comment]
freecadweb.org will still work, so links should still work too. Only once the person is logged in it will switch you automatically to the other domain

**Comment by adrianinsaval** [comment]
Is there anything preventing this change?

**Comment by luzpaz** [comment]
Because of this issue I don't use freecad.org yet with forum threads because it causes way too much confusion for people.
